import { useState } from 'react';
import { Table, Tag, Button, Typography, Alert } from 'antd';
import { useQuery } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import { fetchMyDues } from '../../api/dues';
import { formatCurrency, formatDate, formatMonth } from '../../utils/formatters';
import { STATUS_COLORS } from '../../utils/constants';
import EmptyState from '../../components/common/EmptyState';

const { Title } = Typography;

export default function MyDues() {
  const [page, setPage] = useState(1);
  const navigate = useNavigate();

  const { data, isLoading } = useQuery({
    queryKey: ['my-dues-list', page],
    queryFn: () => fetchMyDues({ page, limit: 20, status: undefined }),
  });

  const columns = [
    { title: 'Month', dataIndex: 'month', key: 'month', render: (v) => formatMonth(v) },
    { title: 'Due Amount', dataIndex: 'amount', key: 'amount', render: (v) => <strong>{formatCurrency(v)}</strong> },
    { title: 'Paid Amount', dataIndex: 'paidAmount', key: 'paidAmount', render: (v) => formatCurrency(v) },
    {
      title: 'Status',
      dataIndex: 'status',
      key: 'status',
      render: (v) => <Tag color={STATUS_COLORS[v]}>{v?.toUpperCase()}</Tag>,
    },
    { title: 'Due Date', dataIndex: 'dueDate', key: 'dueDate', render: (v) => formatDate(v) },
    {
      title: 'Action',
      key: 'action',
      width: 110,
      render: (_, record) =>
        record.status !== 'paid' ? (
          <Button
            type="primary"
            size="small"
            onClick={() => navigate('/pay', { state: { due: record } })}
          >
            Pay Now
          </Button>
        ) : (
          <Tag color="green">Paid</Tag>
        ),
    },
  ];

  const unpaid = (data?.data || []).filter((d) => d.status !== 'paid');

  return (
    <div>
      <Title level={3}>My Maintenance Dues</Title>
      {unpaid.length > 0 && (
        <Alert
          type="warning"
          showIcon
          style={{ marginBottom: 16, borderRadius: 8 }}
          message={`You have ${unpaid.length} pending due${unpaid.length > 1 ? 's' : ''}`}
          action={
            <Button size="small" type="primary" onClick={() => navigate('/pay')}>
              Pay Now
            </Button>
          }
        />
      )}
      <Table
        dataSource={data?.data || []}
        columns={columns}
        rowKey="id"
        loading={isLoading}
        scroll={{ x: 600 }}
        locale={{
          emptyText: (
            <EmptyState
              description="No dues found. Dues are generated by the admin each month."
            />
          ),
        }}
        pagination={{
          current: page,
          pageSize: 20,
          total: data?.total || 0,
          onChange: setPage,
        }}
      />
    </div>
  );
}
